version: '2.0'
services:
  vizdemo-backend:
    image: ghoranyi/docker-intuition-backend
    ports:
      - 8080:8080
      - 8878:8878
      - 9200:9200
  docker-agent:
    image: ghoranyi/docker-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - vizdemo-backend
    links:
      - vizdemo-backend:vizdemo-backend
